# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
        TEST_RESULTS: /tmp/test-results

    working_directory: /go/src/github.com/msiebuhr/ucs
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run: go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Unit tests
          command: go test -v -race $(go list ./... | grep -v /vendor/) 2>&1 | go-junit-report > $TEST_RESULTS/report.xml

      - run:
          name: Bench
          command: go test -bench=. -run=NONE ./... > $TEST_RESULTS/benchmark.txt

      - run:
          name: Bench-mem
          command: go test -bench=. -run=NONE -benchmem ./... > $TEST_RESULTS/benchmark-mem.txt

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output


      - store_test_results:
          path: /tmp/test-results