# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

executors:
    golang:
        docker:
            - image: circleci/golang:1.10
        working_directory: /go/src/github.com/msiebuhr/ucs

jobs:
  build:
    executor: golang

    environment:
        TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: go fmt
          command: |
              go fmt ./...
              git diff --exit-code

      - run: go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v -race $(go list ./... | grep -v /vendor/) | tee ${TEST_RESULTS}/go-test.out

      - run:
          name: Binaries
          command: |
              go build -race -ldflags "-extldflags '-static'" -o /tmp/bin/ucs-linux-x64 ./cmd/ucs/
              go build -race -ldflags "-extldflags '-static'" -o /tmp/bin/ucs-test-linux-x64 ./cmd/ucs-test/
              go build -race -ldflags "-extldflags '-static'" -o /tmp/bin/ucs-bender-linux-x64 ./cmd/ucs-bender/

      - store_artifacts:
          path: /tmp/bin/
          destination: binaries

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  benchmark:
    executor: golang

    environment:
        TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      #- run:
      #    name: Generate
      #    command: |
      #        go get -u github.com/mjibson/esc
      #        go generate ./...
      #        git diff --exit-code ./frontend/

      - run:
          name: Bench
          command: go test -bench=. -run=NONE ./... | tee $TEST_RESULTS/benchmark.txt

      - run:
          name: Bench-mem
          command: go test -bench=. -run=NONE -benchmem ./... | tee $TEST_RESULTS/benchmark-mem.txt

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

workflows:
    version: 2
    default:
        jobs:
            - build
            - benchmark:
                requires:
                    - build
