name: Go
on: [push]
jobs:

  test:
    name: Format
    runs-on: [linux]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Go format
      run: |
        go fmt ./...
        git diff --exit-code

  build:
    name: Build
    runs-on: [linux, macOS-latest]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test ./...

    - name: Build
      run: |
        go build -v ./cmd/ucs
        go build -v ./cmd/ucs-bender
